# Site settings
title: Devon on Devops
email: devonfinninger@gmail.com
description: >
  A collection of things I find interesting near the intersection
  of development and operations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dfinninger.github.io" # the base hostname & protocol for your site
twitter_username: dfinninger
github_username:  dfinninger

# Build settings
markdown: kramdown
